//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCon.iCAS.WebApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_Balance
    {
        public int AccountsYearID { get; set; }
        public System.DateTime FinYearStartDate { get; set; }
        public System.DateTime FinYearCloseDate { get; set; }
        public int AccountsID { get; set; }
        public Nullable<decimal> FinYearOpeningBalance { get; set; }
        public string FinYearOpeningBalanceType { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_04 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_04 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_05 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_05 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_06 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_06 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_07 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_07 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_08 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_08 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_09 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_09 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_10 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_10 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_11 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_11 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_12 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_12 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_01 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_01 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_02 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_02 { get; set; }
        public Nullable<decimal> Total_DB_Balance_Month_03 { get; set; }
        public Nullable<decimal> Total_CR_Balance_Month_03 { get; set; }
        public Nullable<decimal> Total_DEBIT_Transactions { get; set; }
        public Nullable<decimal> Total_CREDIT_Transactions { get; set; }
        public string VC_FIELD1 { get; set; }
        public string VC_FIELD2 { get; set; }
        public Nullable<int> NU_FIELD1 { get; set; }
        public Nullable<int> NU_FIELD2 { get; set; }
        public Nullable<System.DateTime> DT_FIELD1 { get; set; }
        public Nullable<System.DateTime> DT_FIELD2 { get; set; }
        public string CH_FIELD1 { get; set; }
        public string CH_FIELD2 { get; set; }
        public Nullable<int> AuthorisationID { get; set; }
        public int CompanyID { get; set; }
        public int OfficeID { get; set; }
    }
}
