//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCon.iCAS.WebApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_TranVouchers
    {
        public long VoucherID { get; set; }
        public int TranNumber { get; set; }
        public System.DateTime TranDate { get; set; }
        public string VoucherNumber { get; set; }
        public int OfficeID { get; set; }
        public int CompanyID { get; set; }
        public int AccountsYearId { get; set; }
    }
}
