//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCon.iCAS.WebApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_BookClose
    {
        public int RecordNumber { get; set; }
        public int AccountYearID { get; set; }
        public string AccountYearMonth { get; set; }
        public string IsBookClosed { get; set; }
        public Nullable<int> BookClosedByUserID { get; set; }
        public Nullable<System.DateTime> BookCloseDateTime { get; set; }
        public string VC_FIELD1 { get; set; }
        public string VC_FIELD2 { get; set; }
        public Nullable<int> NU_FIELD1 { get; set; }
        public Nullable<int> NU_FIELD2 { get; set; }
        public Nullable<System.DateTime> DT_FIELD1 { get; set; }
        public Nullable<System.DateTime> DT_FIELD2 { get; set; }
        public string CH_FIELD1 { get; set; }
        public string CH_FIELD2 { get; set; }
        public Nullable<int> AuthorisationID { get; set; }
        public int CompanyID { get; set; }
        public int OfficeID { get; set; }
    }
}
