//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCon.iCAS.WebApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMN_MST_Offices
    {
        public int OfficeID { get; set; }
        public string OfficeName { get; set; }
        public Nullable<int> OfficeTypeID { get; set; }
        public string OfficeCode { get; set; }
        public string Address_TownOrCity { get; set; }
        public string Address_Landmark { get; set; }
        public string Address_PinCode { get; set; }
        public Nullable<int> Address_DistrictID { get; set; }
        public Nullable<int> Address_StateID { get; set; }
        public Nullable<System.DateTime> EstablishmentDate { get; set; }
        public Nullable<int> ParentOfficeID { get; set; }
        public Nullable<int> ManagerEmployeeID { get; set; }
        public string ContactPerson1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string ContactPerson3 { get; set; }
        public string StdCodePhone { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string StdCodeFax { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public Nullable<bool> IsHavingShift { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string VC_FIELD1 { get; set; }
        public string VC_FIELD2 { get; set; }
        public Nullable<int> NU_FIELD1 { get; set; }
        public Nullable<int> NU_FIELD2 { get; set; }
        public Nullable<System.DateTime> DT_FIELD1 { get; set; }
        public Nullable<System.DateTime> DT_FIELD2 { get; set; }
        public string CH_FIELD1 { get; set; }
        public string CH_FIELD2 { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
