//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCon.iCAS.WebApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIB_Transactions
    {
        public int IssueNo { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ACCNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> IssueUpto { get; set; }
        public Nullable<System.DateTime> DepoDate { get; set; }
        public Nullable<decimal> Charge { get; set; }
    }
}
